 
name: callto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1   
  cached_network_image: ^3.4.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1
  socket_io_client: ^3.0.2
  intl: ^0.20.2
  web: ^1.1.0  # For WebRTC support on web platform
  record: ^6.2.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/khushi.jpg
    - assets/images/user.png
    - assets/images/male.jpg
    - assets/images/female.jpg
    - assets/images/girl1.jpg
    - assets/images/girl2.jpg
    - assets/voice/sample.mp3
    - assets/login/logo.png
    - assets/login/homelogo.png
    - assets/login/img1.jpg
    - assets/login/img2.jpg
    - assets/login/img3.jpg
    - assets/login/img4.jpg
    - assets/login/img5.jpg
    - assets/login/img6.jpg
    - assets/login/img7.jpg
    - assets/login/img8.jpg
    - assets/login/img9.jpg
    - assets/login/img10.jpg
    - assets/login/img11.jpg
    - assets/login/img12.jpg
    - assets/login/img13.jpg
    - assets/login/img14.jpg
    - assets/login/img15.jpg
    - assets/login/google_logo.png
    - assets/images/female_profile/avatar2.jpg
    - assets/images/female_profile/avatar3.jpg
    - assets/images/female_profile/avatar4.jpg
    - assets/images/female_profile/avatar5.jpg
    - assets/images/female_profile/avatar6.jpg
    - assets/images/female_profile/avatar7.jpg
    - assets/images/female_profile/avatar8.jpg 
    - assets/images/female_profile/avatar9.jpg 
    - assets/images/female_profile/avatar10.jpg 
    - assets/images/female_profile/avatar11.jpg 
    - assets/images/female_profile/avatar12.jpg 
    - assets/images/female_profile/avatar13.jpg
    - assets/images/female_profile/avatar14.jpg
    - assets/images/female_profile/avatar15.jpg

    - assets/images/male_profile/avatar1.jpg
    - assets/images/male_profile/avatar2.jpg
    - assets/images/male_profile/avatar3.jpg
    - assets/images/male_profile/avatar4.jpg
    - assets/images/male_profile/avatar5.jpg
    - assets/images/male_profile/avatar6.jpg
    - assets/images/male_profile/avatar7.jpg
    - assets/images/male_profile/avatar8.jpg
    - assets/images/male_profile/avatar9.jpg
    - assets/images/male_profile/avatar10.jpg
    - assets/images/male_profile/avatar11.jpg
    - assets/images/male_profile/avatar12.jpg
    - assets/images/male_profile/avatar13.jpg
    - assets/images/male_profile/avatar14.jpg
    - assets/images/male_profile/avatar15.jpg
    - assets/images/male_profile/avatar16.jpg 